--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -44,4 +44,4 @@
         uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
         with:
           version: v1.57.1 # we have a list of linters in our .golangci.yml config file
-          only-new-issues: true
+          only-new-issues: true