--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -49,4 +49,4 @@
           # https://github.com/gopasspw/gopass/blob/master/.github/workflows/golangci-lint.yml#L46
           # https://github.com/gopasspw/gopass/blob/master/Makefile#L136
           version: v2.1.1 # we have a list of linters in our .golangci.yml config file
-          only-new-issues: true
+          only-new-issues: true